apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'
    chart: nginx
    targetRevision: "21.0.6"
    helm:
      valuesObject:
        service:
          type: LoadBalancer

  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
