apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-nginx-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/avinash-ekka/argocd-demo-helm
    targetRevision: HEAD

  destination: 
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
